FROM node:lts-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build:prod

# Install `serve` to run the application.
RUN npm install -g serve


# Run application
#CMD [ "npm", "start" ]
CMD serve -s build

# Uses port which is used by the actual application
EXPOSE 3000